<?php
/**
 * @file
 * Administrative page callbacks for the Login Primary Menu module.
 */

/**
 * Login Primary Menu configuration form.
 */
// function login_primary_menu_configuration_form($form, &$form_state) {
//   // Form values will be saved to this config file. See system_settings_form().
//   $form['#config'] = 'login_primary_menu.settings';

//   // Use $config->get() for default values.
//   $config = config('login_primary_menu.settings');

//   $form['opinion_of_backdrop'] = array(
//     '#type' => 'textfield',
//     '#title' => t('What do you think of Backdrop CMS?'),
//     '#default_value' => $config->get('opinion_of_backdrop'),
//   );

//   return system_settings_form($form);
// }
