<?php
/**
 * @file
 * Install, update, and uninstall functions for the Login Primary Menu module.
 */

/**
 * Upgrade from Drupal 7.
 */
// function login_primary_menu_update_1000() {
//   // Convert D7 variables to config.
//   $config = config('login_primary_menu.settings');
//   $config->set('opinion_of_backdrop', update_variable_get('login_primary_menu_opinion_drupal', 'Awesome!'));
//   $config->save();

//   // Delete D7 variables.
//   update_variable_del('login_primary_menu_opinion_drupal');
// }
