<?php
/**
 * @file
 * Install, update and uninstall functions for the prepopulate module.
 *
 */


/**
 * Implements hook_install().
 */
function prepopulate_install() {
  $ret = array();
  // Ensure that prepopulate sinks to the bottom during hook calls
  // there should be a UI for this at some point.
  $ret[] = db_query("UPDATE {system} SET weight = 10 WHERE name = 'prepopulate'");
  return $ret;
  // Dynamically generated variable data was detected on the following lines.
}

/**
 * Implements hook_update_last_removed().
 */
function prepopulate_update_last_removed() {
  return;
}
