<?php
/**
 * @file
 * Install, update and uninstall functions for the account_activation_reminder module.
 *
 */


/**
 * Migrate account_activation_reminder variables to config.
 */
function account_activation_reminder_update_1000() {
  $config = config('account_activation_reminder.settings');
  $config->set('account_activation_reminder_e-mail_subject', update_variable_get('account_activation_reminder_e-mail_subject', 'Administrative Warning'));
  $config->set('account_activation_reminder_e-mail_body', update_variable_get('account_activation_reminder_e-mail_body', 'ACCOUNT_ACTIVATION_REMINDER_BODY'));
  $config->save();

  update_variable_del('account_activation_reminder_e-mail_subject');
  update_variable_del('account_activation_reminder_e-mail_body');
}

/**
 * Implements hook_install().
 */
function account_activation_reminder_install() {
  // Dynamically generated variable data was detected.
}
