<?php

/**
 * @file
 * Functionality for the Config Translation module.
 */


t("An administrator created an account for you at [site:name]", array(), array('context' => 'config:user.mail:register_admin_created_subject'));

t("[user:name],\n\nA site administrator at [site:name] has created an account for you. You may now log in by clicking this link or copying and pasting it to your browser:\n\n[user:one-time-login-url]\n\nThis link can only be used once to log in and will lead you to a page where you can set your password.\n\nAfter setting your password, you will be able to log in at [site:login-url] in the future using:\n\nusername: [user:name]\npassword: Your password\n\n--  [site:name] team", array(), array('context' => 'config:user.mail:register_admin_created_body'));

t("Account details for [user:name] at [site:name] (pending admin approval)", array(), array('context' => 'config:user.mail:register_pending_approval_subject'));
